import { Header } from '@game-hub/components';

import './global.css';
import Link from 'next/link';

export const metadata = {
  title: 'GameHub',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <main className='flex flex-col h-full justify-between'>
          <div className='flex flex-col grow'>
            <Header title='GameHub'>
              <nav>
                <ul className='flex space-x-4'>
                  <li>
                    <Link href='/' className='hover:underline'>
                      Games
                    </Link>
                  </li>
                  <li>
                    <a href='#about' className='hover:underline'>
                      About
                    </a>
                  </li>
                </ul>
              </nav>
            </Header>
            {children}
          </div>
          {/* </section> */}
          <footer id='about' className='flex items-center justify-center p-4'>
            <p className='text-center text-gray-600'>
              Welcome to the GameHub! This is a demo site for the GameHub
              project.
            </p>
          </footer>
        </main>
      </body>
    </html>
  );
}